// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckEnvironment(arg1) {
  return window['go']['main']['App']['CheckEnvironment'](arg1);
}

export function GetEdgeVersion(arg1) {
  return window['go']['main']['App']['GetEdgeVersion'](arg1);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function StartEdge(arg1) {
  return window['go']['main']['App']['StartEdge'](arg1);
}

export function StopEdge() {
  return window['go']['main']['App']['StopEdge']();
}

export function ValidateConfig(arg1) {
  return window['go']['main']['App']['ValidateConfig'](arg1);
}
