// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {edge} from '../models';

export function CheckEnvironment(arg1:edge.Config):Promise<edge.EnvironmentStatus>;

export function GetEdgeVersion(arg1:edge.Config):Promise<string>;

export function GetStatus():Promise<edge.Status>;

export function StartEdge(arg1:edge.Config):Promise<edge.Status>;

export function StopEdge():Promise<edge.Status>;

export function ValidateConfig(arg1:edge.Config):Promise<void>;
